// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           19
// Async Callback (empty):               1
// Total number of exported functions:  22

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    arbitrage_sc
    (
        init => init
        upgrade => upgrade
        isPaused => is_paused
        isStakingPaused => is_staking_paused
        getStakedTokenId => staked_token_id
        getStakedAmount => staked_amount
        getUserWinnings => user_winnings
        getDevWinnings => dev_winnings
        getOwnerWinningsPercentage => owner_winnings_percentage
        pause => pause
        unpause => unpause
        pauseStaking => pause_staking
        unpauseStaking => unpause_staking
        setStakedToken => set_staked_token
        setOwnerWinningsPercentage => set_owner_winnings_percentage
        withdrawDevWinnings => withdraw_dev_winnings
        executeTrades => execute_trades
        stake => stake
        unstake => unstake
        restakeWinnings => restake_winnings
        claimWinnings => claim_winnings
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
