// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    arbitrage_sc
    (
        init => init
        upgrade => upgrade
        isPaused => is_paused
        getStakedTokenId => staked_token_id
        getStakedAmount => staked_amount
        getUserWinnings => user_winnings
        getDevWinnings => dev_winnings
        pause => pause
        unpause => unpause
        setStakedToken => set_staked_token
        withdrawDevWinnings => withdraw_dev_winnings
        executeTrades => execute_trades
        stake => stake
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
