import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const projectRoot = path.resolve(__dirname, '..')
const stateFilePath = path.resolve(projectRoot, '../arbitrage-sc/interactor/state.toml')
const outputDir = path.resolve(projectRoot, 'src/generated')
const outputPath = path.resolve(outputDir, 'stateContract.ts')

function extractContractAddress(tomlContent) {
  const match = tomlContent.match(/contract_address\s*=\s*"([^"]+)"/)
  if (!match) {
    throw new Error(`Could not find 'contract_address' in ${stateFilePath}`)
  }

  return match[1]
}

try {
  const stateToml = readFileSync(stateFilePath, 'utf8')
  const contractAddress = extractContractAddress(stateToml)

  mkdirSync(outputDir, { recursive: true })

  const output = `// Auto-generated by scripts/syncState.mjs. Do not edit manually.\nexport const devnetContractAddressFromState = '${contractAddress}'\n`

  writeFileSync(outputPath, output)
  console.log(`Synced contract address from ${stateFilePath} -> ${outputPath}`)
} catch (error) {
  console.error(`Failed to sync state.toml contract address: ${error.message}`)
  process.exit(1)
}
